# Generated by Django 5.1 on 2024-09-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_supervisor',
        ),
    ]
