# Generated by Django 5.1 on 2024-09-08 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_employee_employee_supervisor'),
        ('User', '0001_initial'),
        ('company', '0005_remove_manager_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
