# Generated by Django 5.1 on 2025-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_employees_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
