# Generated by Django 5.1 on 2024-09-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_employee_employee_supervisor'),
        ('User', '0001_initial'),
        ('company', '0003_payroll_manager_alter_payroll_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_reviews', to='company.manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceassignonprojects',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_data', to='company.project'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='User.department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_data', to='Employee.employee'),
        ),
    ]
