# Generated by Django 5.1 on 2024-09-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_project_employees_performancereview_review_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
    ]
