# Generated by Django 5.1 on 2025-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_manager_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
